# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
install:
  - Rscript -e 'install.packages("magrittr", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("haven", repos = "http://cran.rstudio.com")'
  - Rscript -e 'install.packages("usethis", repos = "http://cran.rstudio.com")'
r_packages:
   - covr

script:
- R CMD build .

after_success:
  - Rscript -e 'usethis::use_coverage()'
